#!/usr/bin/env perl
package Consumer;
use Moose;
use RabbitFoot;
use Data::Dumper;
use namespace::autoclean;

with qw/
    MooseX::Getopt
    MQ
/;

sub run {
    my $self = shift;
    my $rf = $self->_get_mq;
    my $ch = $self->_get_channel($rf);
    $self->_bind_anon_queue_to_firehose($ch);
    my $done = AnyEvent->condvar;
    $ch->consume(
        on_consume => sub {
            my $message = shift;
            print $message->{deliver}->method_frame->routing_key,
                ': ', $message->{body}->payload, "\n";
        },
    );
    $done->recv; # Go into the event loop forever.
}

__PACKAGE__->meta->make_immutable;
__PACKAGE__->new_with_options->run unless caller;
1;

