#!/usr/bin/env perl
package Emitter;
use Moose;
use RabbitFoot;
use Data::Dumper;
use JSON qw/to_json/;
use namespace::autoclean;

with qw/
    MooseX::Getopt
    MQ
/;

sub run {
    my $self = shift;
    my $rf = $self->_get_mq;
    my $ch = $self->_get_channel($rf);
    $ch->publish(
        body => q[{"__CLASS__": "CatalystX::JobServer::Job::Test::RunForThirtySeconds", "val": 42}],
        exchange => 'jobs',
        routing_key => '#',
    );
    $rf->{_ar}->drain_writes;
}

__PACKAGE__->meta->make_immutable;
__PACKAGE__->new_with_options->run unless caller;
1;

